/**
 * generated by Xtext 2.25.0
 */
package dk.sdu.mmmi.mdsd.scoping;

import dk.sdu.mmmi.mdsd.math.MathExp;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EReference;
import org.eclipse.xtext.scoping.IScope;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class MathScopeProvider extends AbstractMathScopeProvider {
  public IScope getScope(final EObject context, final EReference ref) {
    throw new Error("Unresolved compilation problems:"
      + "\nComparison cannot be resolved to a type."
      + "\nThe method or field members is undefined for the type MathExp"
      + "\nType mismatch: cannot convert implicit first argument from MathScopeProvider to MathExp"
      + "\nType mismatch: cannot convert from IScope to MathExp"
      + "\nfilter cannot be resolved");
  }
  
  public IScope getBase(final MathExp math) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field members is undefined for the type IScope"
      + "\nType mismatch: cannot convert from IScope to MathExp"
      + "\nfilter cannot be resolved");
  }
}
